### ISSUE TITLE
`NEXT_PUBLIC_HELIUS_API_KEY` is not valid, it would make sense to reuse RPC endpoint user has inputed at step 0

### ISSUE THREAD

**Issue by kustrun** [SolWorks-Dev/soldisperse#6]
The API-KEY read from environmental variables is invalid, user can't change it. To make the app work it would make sense to replace usages of `NEXT_PUBLIC_HELIUS_API_KEY` with the RPC url user has provided at step 0 (in this case user can arbitrary RPC URL with or without any API-KEY). 

https://github.com/SolWorks-Dev/soldisperse/blob/793a8a974237715e8286299a4246b45f3c7c8be8/app/page.tsx#L108

**Comment by zhe-t** [comment]
Fixed in https://github.com/SolWorks-Dev/soldisperse/commit/672a87bbc6a5b1b8974e2527eb515aed23ffab7b, input for API key added as standalone input. Thanks for reporting! 🫶
